/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jonjelly;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mrpds
 */
public class Logout extends javax.swing.JFrame {

    /**
     * Creates new form Logout
     */
    public Logout() {
        initComponents();
        setTitle("Logout");
        System.out.println("Menjalankan System Logout Jon!");
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        ThanksIcon = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Shutdown = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(45, 45, 45));

        ThanksIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ThanksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/brand/thanks.png"))); // NOI18N

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/system login.png"))); // NOI18N
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });

        Shutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/system shutdown.png"))); // NOI18N
        Shutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShutdownMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(ThanksIcon)
                .addGap(55, 55, 55)
                .addComponent(Login)
                .addGap(37, 37, 37)
                .addComponent(Shutdown)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(ThanksIcon))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Shutdown)
                            .addComponent(Login))))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Button Back Login
    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
        System.out.println("Back To Login Jon!");
        JonJelly jj=new JonJelly();
        jj.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(false);
        jj.setVisible(true);
    }//GEN-LAST:event_LoginMouseClicked

    // Button Shutdown
    private void ShutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShutdownMouseClicked
        // TODO add your handling code here:
        System.out.println("Running System Shutdown Jon!");
        int res = JOptionPane.showConfirmDialog(null, "Do You want to Shutdown?", "Shutdown", JOptionPane.YES_NO_OPTION);
        switch (res) {
            case JOptionPane.YES_OPTION:
            System.out.println("Shutdown System JonJelly!");
            JOptionPane.showMessageDialog(null, "Thank You!","Succes Shutdown", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
            break;
            case JOptionPane.NO_OPTION:
            System.out.println("Canceled Shutdown System JonJelly!");
            JOptionPane.showMessageDialog(null, "Shutdown is Canceled!","Cancel Shutdown", JOptionPane.INFORMATION_MESSAGE);
            break;
        }
        
    }//GEN-LAST:event_ShutdownMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JonJelly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JonJelly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JonJelly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JonJelly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Logout LGT=new Logout();
            LGT.setExtendedState(JFrame.MAXIMIZED_BOTH);
            LGT.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Shutdown;
    private javax.swing.JLabel ThanksIcon;
    // End of variables declaration//GEN-END:variables
}
