/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jonjelly.view.staf;

import config.Database;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import jonjelly.controllers.Staf;

/**
 *
 * @author mrpds
 */
public class UserManage extends javax.swing.JFrame {
    private DefaultTableModel ModelUser;
    /**
     * Creates new form UserManage
     */
    
    public UserManage() {
        initComponents();
        setTitle("User Manage");
        System.out.println("Selamat Datang Di Halaman UserManage Staf Jon!");
        this.setLocationRelativeTo(this);
        
        //memberi penamaan pada judul kolom TableUser;
             ModelUser = new DefaultTableModel ( );
             TableUser.setModel(ModelUser);
             ModelUser.addColumn("ID");
             ModelUser.addColumn("NAMA");
             ModelUser.addColumn("JABATAN");
             ModelUser.addColumn("USERNAME");
             ModelUser.addColumn("PASSWORD");
             ModelUser.addColumn("EMAIL");
             ModelUser.addColumn("NO TELP");
             ModelUser.addColumn("KELAMIN");
             ModelUser.addColumn("ALAMAT");
             getDataUser();
             kode();
    }
    
        
    public void FilterAngka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "HARAP MASUKAN ANGKA SAJA!", "NOTICE VALIDATION", JOptionPane.WARNING_MESSAGE);
           InputNoTelp.setText("");
       }
   }
    public void FilterHuruf(KeyEvent a){
       if(Character.isDigit(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "HARAP MASUKAN HURUF SAJA!", "NOTICE VALIDATION", JOptionPane.WARNING_MESSAGE);
           InputNama.setText("");
       }
   }

    // Ambil data user untuk cetak di TableUser
    public void getDataUser( ){
     //menghapus isi table TabelUser
        ModelUser.getDataVector( ).removeAllElements( );
        ModelUser.fireTableDataChanged( );

        try{
            Statement stat = (Statement) Database.getKoneksi( ).createStatement( );
            String sql        = "SELECT * FROM user ORDER BY jabatan DESC";
            ResultSet res   = stat.executeQuery(sql);
            while(res.next ()){
                 Object[ ] obj = new Object[9];
                 obj[0] = res.getString("id_user");
                 obj[1] = res.getString("nama_user");
                 obj[2] = res.getString("jabatan");
                 obj[3] = res.getString("username_user");
                 obj[4] = res.getString("password_user");
                 obj[5] = res.getString("email_user");
                 obj[6] = res.getString("no_telp");
                 obj[7] = res.getString("jenis_kelamin");
                 obj[8] = res.getString("alamat");

                 ModelUser.addRow(obj);
             }
         }catch(SQLException err){
                System.out.println("Error Load Data User");
         }
    }
    //Create Auto number
    private void kode() {
        try {
            Connection c = Database.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM user ORDER by id_user desc";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String iduser = r.getString("id_user").substring(1);
                String AN = "" + (Integer.parseInt(iduser) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "000";
                } else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }

                InputIdUser.setText("U" + Nol + AN);
            } else {
                InputIdUser.setText("U0001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jabatan = new javax.swing.ButtonGroup();
        JenisKelamin = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        icon_header = new javax.swing.JLabel();
        TagPage = new javax.swing.JLabel();
        BtnBack = new javax.swing.JLabel();
        SearchUser = new javax.swing.JLabel();
        LIdUser = new javax.swing.JLabel();
        LNamaUser = new javax.swing.JLabel();
        LJenisKelamin = new javax.swing.JLabel();
        LNoTelp = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        LAlamat = new javax.swing.JLabel();
        LUsername = new javax.swing.JLabel();
        LPassword = new javax.swing.JLabel();
        LJabatan = new javax.swing.JLabel();
        InputSearch = new javax.swing.JTextField();
        InputIdUser = new javax.swing.JTextField();
        InputNama = new javax.swing.JTextField();
        InputNoTelp = new javax.swing.JTextField();
        InputEmail = new javax.swing.JTextField();
        InputUsername = new javax.swing.JTextField();
        InputPassword = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        InputAlamat = new javax.swing.JTextArea();
        JbtnStaf = new javax.swing.JRadioButton();
        JbtnKaryawan = new javax.swing.JRadioButton();
        JkLaki = new javax.swing.JRadioButton();
        JkPerempuan = new javax.swing.JRadioButton();
        BtnTambah = new javax.swing.JButton();
        BtnUbah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(45, 45, 45));

        icon_header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/brand/header.png"))); // NOI18N

        TagPage.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TagPage.setForeground(new java.awt.Color(190, 190, 190));
        TagPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/tag_page.png"))); // NOI18N
        TagPage.setText("User Manage");

        BtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/back_header.png"))); // NOI18N
        BtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBackMouseClicked(evt);
            }
        });

        SearchUser.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        SearchUser.setForeground(new java.awt.Color(102, 102, 102));
        SearchUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/search.png"))); // NOI18N

        LIdUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LIdUser.setForeground(new java.awt.Color(190, 190, 190));
        LIdUser.setText("ID USER");

        LNamaUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LNamaUser.setForeground(new java.awt.Color(190, 190, 190));
        LNamaUser.setText("Nama");

        LJenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LJenisKelamin.setForeground(new java.awt.Color(190, 190, 190));
        LJenisKelamin.setText("Jenis Kelamin");

        LNoTelp.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LNoTelp.setForeground(new java.awt.Color(190, 190, 190));
        LNoTelp.setText("No Telpon");

        LEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LEmail.setForeground(new java.awt.Color(190, 190, 190));
        LEmail.setText("Email");

        LAlamat.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LAlamat.setForeground(new java.awt.Color(190, 190, 190));
        LAlamat.setText("Alamat");

        LUsername.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LUsername.setForeground(new java.awt.Color(190, 190, 190));
        LUsername.setText("Username");

        LPassword.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LPassword.setForeground(new java.awt.Color(190, 190, 190));
        LPassword.setText("Password");

        LJabatan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LJabatan.setForeground(new java.awt.Color(190, 190, 190));
        LJabatan.setText("Jabatan");

        InputSearch.setBackground(new java.awt.Color(45, 45, 45));
        InputSearch.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        InputSearch.setForeground(new java.awt.Color(102, 102, 102));
        InputSearch.setText("ex: devi/staf/perempuan");
        InputSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InputSearchMouseEntered(evt);
            }
        });
        InputSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputSearchKeyReleased(evt);
            }
        });

        InputIdUser.setEditable(false);
        InputIdUser.setBackground(new java.awt.Color(45, 45, 45));
        InputIdUser.setForeground(new java.awt.Color(190, 190, 190));

        InputNama.setBackground(new java.awt.Color(45, 45, 45));
        InputNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InputNama.setForeground(new java.awt.Color(190, 190, 190));
        InputNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputNamaKeyReleased(evt);
            }
        });

        InputNoTelp.setBackground(new java.awt.Color(45, 45, 45));
        InputNoTelp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InputNoTelp.setForeground(new java.awt.Color(190, 190, 190));
        InputNoTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputNoTelpKeyReleased(evt);
            }
        });

        InputEmail.setBackground(new java.awt.Color(45, 45, 45));
        InputEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InputEmail.setForeground(new java.awt.Color(190, 190, 190));

        InputUsername.setBackground(new java.awt.Color(45, 45, 45));
        InputUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InputUsername.setForeground(new java.awt.Color(190, 190, 190));

        InputPassword.setBackground(new java.awt.Color(45, 45, 45));
        InputPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InputPassword.setForeground(new java.awt.Color(190, 190, 190));

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableUser);

        InputAlamat.setBackground(new java.awt.Color(45, 45, 45));
        InputAlamat.setColumns(20);
        InputAlamat.setForeground(new java.awt.Color(204, 204, 204));
        InputAlamat.setRows(5);
        jScrollPane1.setViewportView(InputAlamat);

        Jabatan.add(JbtnStaf);
        JbtnStaf.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        JbtnStaf.setForeground(new java.awt.Color(255, 255, 255));
        JbtnStaf.setText("Staf");

        Jabatan.add(JbtnKaryawan);
        JbtnKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        JbtnKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        JbtnKaryawan.setText("Karyawan");

        JenisKelamin.add(JkLaki);
        JkLaki.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        JkLaki.setForeground(new java.awt.Color(255, 255, 255));
        JkLaki.setText("Laki-Laki");

        JenisKelamin.add(JkPerempuan);
        JkPerempuan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        JkPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        JkPerempuan.setText("Perempuan");

        BtnTambah.setBackground(new java.awt.Color(91, 59, 255));
        BtnTambah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnTambah.setForeground(new java.awt.Color(255, 255, 255));
        BtnTambah.setText("TAMBAH");
        BtnTambah.setBorder(null);
        BtnTambah.setBorderPainted(false);
        BtnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnUbah.setBackground(new java.awt.Color(240, 123, 63));
        BtnUbah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnUbah.setForeground(new java.awt.Color(255, 255, 255));
        BtnUbah.setText("UBAH");
        BtnUbah.setBorder(null);
        BtnUbah.setBorderPainted(false);
        BtnUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });

        BtnHapus.setBackground(new java.awt.Color(234, 84, 85));
        BtnHapus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnHapus.setForeground(new java.awt.Color(255, 255, 255));
        BtnHapus.setText("HAPUS");
        BtnHapus.setBorder(null);
        BtnHapus.setBorderPainted(false);
        BtnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnReset.setBackground(new java.awt.Color(102, 102, 102));
        BtnReset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnReset.setForeground(new java.awt.Color(255, 255, 255));
        BtnReset.setText("RESET");
        BtnReset.setBorder(null);
        BtnReset.setBorderPainted(false);
        BtnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(icon_header)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBack))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LNamaUser)
                                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(BackgroundLayout.createSequentialGroup()
                                            .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(BtnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LAlamat)
                                            .addComponent(InputNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LNoTelp))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(InputIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LIdUser))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LJenisKelamin)
                                    .addComponent(LEmail)
                                    .addComponent(LUsername)
                                    .addComponent(InputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LPassword)
                                    .addComponent(LJabatan)
                                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                            .addComponent(JbtnStaf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JbtnKaryawan))
                                        .addComponent(InputPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                            .addComponent(JkLaki)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JkPerempuan))
                                        .addComponent(InputEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(TagPage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(InputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchUser)))))
                .addGap(22, 22, 22))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_header)
                    .addComponent(BtnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(LIdUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LNamaUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LNoTelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LAlamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(InputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SearchUser))
                            .addGap(57, 57, 57)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(BackgroundLayout.createSequentialGroup()
                            .addComponent(LJenisKelamin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JkPerempuan)
                                .addComponent(JkLaki))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(InputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LUsername)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(InputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LPassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LJabatan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JbtnStaf)
                                .addComponent(JbtnKaryawan)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(TagPage)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   
    // Button Back Header
    private void BtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBackMouseClicked
        // TODO add your handling code here:
        System.out.println("Kita Balik Ke Controllers Staf Jon!");
        Staf st=new Staf();
        st.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(false);
        st.setVisible(true);
    }//GEN-LAST:event_BtnBackMouseClicked

    // Button Created user
    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        // TODO add your handling code here:
        if( 
            InputIdUser.getText().equals("")||
            InputNama.getText().equals("") || 
            JbtnStaf.getText().equals("") ||
            InputUsername.getText().equals("")|| 
            InputPassword.getText().equals("")|| 
            InputEmail.getText().equals("") ||
            InputNoTelp.getText().equals("") ||
            JkLaki.getText().equals("") ||  
            InputAlamat.getText().equals("") 
           ){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "JONJELLY", JOptionPane.WARNING_MESSAGE);
        }else{
            String iduser = InputIdUser.getText();
            String namauser = InputNama.getText();
            String jabatanuser ="";
            if(JbtnStaf.isSelected()){
                jabatanuser = JbtnStaf.getText();
            }else{
                jabatanuser = JbtnKaryawan.getText();
            }
            String usernameuser = InputUsername.getText();
            String passworduser = InputPassword.getText();
            String emailuser = InputEmail.getText();
            String notelpuser = InputNoTelp.getText();
            String jeniskelaminuser ="";
            if(JkLaki.isSelected()){
                jeniskelaminuser = JkLaki.getText();
            }else{
                jeniskelaminuser = JkPerempuan.getText();
            }
            String alamatuser = InputAlamat.getText();
            try {
                Connection c = Database.getKoneksi();
                String sql = "INSERT INTO user VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, iduser);
                p.setString(2, namauser);
                p.setString(3, jabatanuser);
                p.setString(4, usernameuser);
                p.setString(5, passworduser);
                p.setString(6, emailuser);
                p.setString(7, notelpuser);
                p.setString(8, jeniskelaminuser);
                p.setString(9, alamatuser);
                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                System.out.println("Terjadi Error Insert ke table User");
            } finally {
                getDataUser();
                kode();
                InputNama.setText("");
                Jabatan.clearSelection();
                InputUsername.setText("");
                InputPassword.setText("");
                InputEmail.setText("");
                InputNoTelp.setText("");
                JenisKelamin.clearSelection();
                InputAlamat.setText("");
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan", "JONJELLY", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    // Table user Into textfield
    private void TableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseClicked
        // TODO add your handling code here:
        BtnTambah.setEnabled(false);
        InputNama.setEnabled(false);
        JkLaki.setEnabled(false);
        int i = TableUser.getSelectedRow();
        if (i == -1) {
            return;
        }
        String iduser = (String) ModelUser.getValueAt(i, 0);
        InputIdUser.setText(iduser);
        InputIdUser.setEnabled(false);

        String namauser = (String) ModelUser.getValueAt(i, 1);
        InputNama.setText(namauser);
        
        String jabatanuser = (String) ModelUser.getValueAt(i, 2);
        String jbt ="Staf";
        if(jabatanuser.equals(jbt)){
            JbtnStaf.setSelected(true);
        }else{
            JbtnKaryawan.setSelected(true);
        }
        
        String usernameuser = (String) ModelUser.getValueAt(i, 3);
        InputUsername.setText(usernameuser);
        
        String passworduser = (String) ModelUser.getValueAt(i, 4);
        InputPassword.setText(passworduser);
        
        String emailuser = (String) ModelUser.getValueAt(i, 5);
        InputEmail.setText(emailuser);
        
        String notelpuser = (String) ModelUser.getValueAt(i, 6);
        InputNoTelp.setText(notelpuser);
        
        String jeniskelaminuser = (String) ModelUser.getValueAt(i, 7);
        String jk ="Laki-Laki";
        if(jeniskelaminuser.equals(jk)){
            JkLaki.setSelected(true);
        }else{
            JkPerempuan.setSelected(true);
        }
        
        String alamatuser = (String) ModelUser.getValueAt(i, 8);
        InputAlamat.setText(alamatuser);
    }//GEN-LAST:event_TableUserMouseClicked

    // Search replace text
    private void InputSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputSearchMouseClicked
        // TODO add your handling code here:
        InputSearch.setText("");
    }//GEN-LAST:event_InputSearchMouseClicked

    // TextField Search User
    private void InputSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputSearchKeyReleased
        // TODO add your handling code here:
        ModelUser.getDataVector().removeAllElements();
        ModelUser.fireTableDataChanged();

        try {
            Connection c = Database.getKoneksi();
            Statement s = c.createStatement();

            String sql = "select * from user where id_user like '%" + InputSearch.getText() +
            "%' or id_user like'%" + InputSearch.getText() +
            "%' or nama_user like'" + InputSearch.getText() +
            "%' or jabatan like'%" + InputSearch.getText() +
            "%' or username_user like'%" + InputSearch.getText() +
            "%' " + "or jenis_kelamin like'%" + InputSearch.getText() + "%'";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[ ] CariUser = new Object[9];
                CariUser[0] = r.getString("id_user");
                CariUser[1] = r.getString("nama_user");
                CariUser[2] = r.getString("jabatan");
                CariUser[3] = r.getString("username_user");
                CariUser[4] = r.getString("password_user");
                CariUser[5] = r.getString("email_user");
                CariUser[6] = r.getString("no_telp");
                CariUser[7] = r.getString("jenis_kelamin");
                CariUser[8] = r.getString("alamat");
                ModelUser.addRow(CariUser);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error Search data user");
        }
        
    }//GEN-LAST:event_InputSearchKeyReleased

    // Button Reset
    private void BtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseClicked
        // TODO add your handling code here:
        kode();
        InputNama.setText("");
        Jabatan.clearSelection();
        InputUsername.setText("");
        InputPassword.setText("");
        InputEmail.setText("");
        InputNoTelp.setText("");
        JenisKelamin.clearSelection();
        InputAlamat.setText("");
        BtnTambah.setEnabled(true);
        InputNama.setEnabled(true);
        JkLaki.setEnabled(true);
        InputIdUser.setEnabled(true);
    }//GEN-LAST:event_BtnResetMouseClicked

    // Button Delete User
    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        //System.out.println("Running System Shutdown Jon!");
        int res = JOptionPane.showConfirmDialog(null, "Do You want to DELETE USER?", "DELETE USER", JOptionPane.YES_NO_OPTION);
        switch (res) {
            case JOptionPane.YES_OPTION:
                if( InputIdUser.getText().equals("")||
                    InputNama.getText().equals("") || 
                    JbtnStaf.getText().equals("") ||
                    InputUsername.getText().equals("")|| 
                    InputPassword.getText().equals("")|| 
                    InputEmail.getText().equals("") ||
                    InputNoTelp.getText().equals("") ||
                    JkLaki.getText().equals("") ||  
                    InputAlamat.getText().equals("") 
                   ){JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "DELETE USER", JOptionPane.WARNING_MESSAGE);}
                else{
                    try {
                        String sql ="delete from user where id_user='"+InputIdUser.getText()+"'";
                        java.sql.Connection conn=(Connection)Database.getKoneksi();
                        java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(this, "Data berhasil di hapus!");
                        getDataUser();
                        InputNama.setText("");
                        Jabatan.clearSelection();
                        InputUsername.setText("");
                        InputPassword.setText("");
                        InputEmail.setText("");
                        InputNoTelp.setText("");
                        JenisKelamin.clearSelection();
                        InputAlamat.setText("");
                        BtnTambah.setEnabled(true);
                        InputNama.setEnabled(true);
                        JkLaki.setEnabled(true);
                        InputIdUser.setEnabled(true);
                    }catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                        }
                    }
            break;
            case JOptionPane.NO_OPTION:
                kode();
                InputNama.setText("");
                Jabatan.clearSelection();
                InputUsername.setText("");
                InputPassword.setText("");
                InputEmail.setText("");
                InputNoTelp.setText("");
                JenisKelamin.clearSelection();
                InputAlamat.setText("");
                BtnTambah.setEnabled(true);
                InputNama.setEnabled(true);
                JkLaki.setEnabled(true);
                InputIdUser.setEnabled(true);
            break;
        }
        
    }//GEN-LAST:event_BtnHapusActionPerformed

    // Button Update User
    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        // TODO add your handling code here:
        if( 
            InputIdUser.getText().equals("")||
            InputNama.getText().equals("") || 
            JbtnStaf.getText().equals("") ||
            InputUsername.getText().equals("")|| 
            InputPassword.getText().equals("")|| 
            InputEmail.getText().equals("") ||
            InputNoTelp.getText().equals("") ||
            JkLaki.getText().equals("") ||  
            InputAlamat.getText().equals("") 
           ){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "JONJELLY", JOptionPane.WARNING_MESSAGE);
        }else{
            int i = TableUser.getSelectedRow();
            if (i == -1) {
                return;
            }
            String iduser = (String) ModelUser.getValueAt(i, 0);
            InputIdUser.setText(iduser);
            try {
                String jabatanuser ="";
                if(JbtnStaf.isSelected()){
                    jabatanuser = JbtnStaf.getText();
                }else{
                    jabatanuser = JbtnKaryawan.getText();
                }
                Connection c = Database.getKoneksi();
                String sql = "UPDATE  user SET "
                            + "jabatan =  '" + jabatanuser + "',"
                            + " username_user='"+ InputUsername.getText() + "',"
                            + " password_user='"+ InputPassword.getText() + "',"
                            + " email_user='"+ InputEmail.getText() + "',"
                            + " no_telp='"+ InputNoTelp.getText() + "',"
                            + " alamat='"+ InputAlamat.getText() +"' WHERE  id_user ='" + InputIdUser.getText() + "'";
                PreparedStatement p = c.prepareStatement(sql);
                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                System.out.println("Terjadi Error Update data user");
            } finally {
                getDataUser();
                kode();
                InputNama.setText("");
                Jabatan.clearSelection();
                InputUsername.setText("");
                InputPassword.setText("");
                InputEmail.setText("");
                InputNoTelp.setText("");
                JenisKelamin.clearSelection();
                InputAlamat.setText("");
                BtnTambah.setEnabled(true);
                InputNama.setEnabled(true);
                JkLaki.setEnabled(true);
                InputIdUser.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "JONJELLY", JOptionPane.INFORMATION_MESSAGE);
            }
           }
    }//GEN-LAST:event_BtnUbahActionPerformed

    // Textfield input nama user
    private void InputNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNamaKeyReleased
        // TODO add your handling code here:
        FilterHuruf(evt);
    }//GEN-LAST:event_InputNamaKeyReleased

    // Textfield input notelp nama user
    private void InputNoTelpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNoTelpKeyReleased
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_InputNoTelpKeyReleased

    // Textfield replace text search
    private void InputSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputSearchMouseEntered
        // TODO add your handling code here:
        InputSearch.setText("");
    }//GEN-LAST:event_InputSearchMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            UserManage UM=new UserManage();
            UM.setExtendedState(JFrame.MAXIMIZED_BOTH);
            UM.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BtnBack;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JTextArea InputAlamat;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputIdUser;
    private javax.swing.JTextField InputNama;
    private javax.swing.JTextField InputNoTelp;
    private javax.swing.JTextField InputPassword;
    private javax.swing.JTextField InputSearch;
    private javax.swing.JTextField InputUsername;
    private javax.swing.ButtonGroup Jabatan;
    private javax.swing.JRadioButton JbtnKaryawan;
    private javax.swing.JRadioButton JbtnStaf;
    private javax.swing.ButtonGroup JenisKelamin;
    private javax.swing.JRadioButton JkLaki;
    private javax.swing.JRadioButton JkPerempuan;
    private javax.swing.JLabel LAlamat;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LIdUser;
    private javax.swing.JLabel LJabatan;
    private javax.swing.JLabel LJenisKelamin;
    private javax.swing.JLabel LNamaUser;
    private javax.swing.JLabel LNoTelp;
    private javax.swing.JLabel LPassword;
    private javax.swing.JLabel LUsername;
    private javax.swing.JLabel SearchUser;
    private javax.swing.JTable TableUser;
    private javax.swing.JLabel TagPage;
    private javax.swing.JLabel icon_header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
